// Event.h
//
// Copyright (c) The Dasher Team
//
// Signal/Slot (Publisher/Subscriber) pattern for DasherCore's internal
// event system. Used for parameter-change notifications, edit events,
// and view/model lifecycle notifications.
//
// Design notes:
//
// This replaces the original void*-keyed unordered_map approach with a
// std::map for deterministic broadcast order. The original system had
// two problems:
//
//   1. unordered_map<void*, fn> iterated in hash-dependent order,
//      which was non-deterministic on Linux (libstdc++ randomizes hash
//      seeds per process). This could cause subtle ordering bugs if
//      multiple subscribers' side effects compound.
//
//   2. Manual Unsubscribe() — if a subscriber forgot to unsubscribe
//      before destruction, the Event held a dangling pointer. This
//      is the classic C++ signal/slot lifetime hazard.
//
// The fix addresses both:
//   - std::map gives sorted (deterministic) iteration order
//   - The Subscription RAII guard auto-unsubscribes on destruction
//
// Existing callers using Subscribe(void*, fn) / Unsubscribe(void*)
// continue to work without changes. New code should prefer the RAII
// pattern: store the returned Subscription as a member, and let it
// auto-clean on destruction.

#pragma once

#include <string>
#include <functional>
#include <map>
#include <cstdint>

namespace Dasher {
class CEditEvent;
class CDasherNode; // fwd decl
} // namespace Dasher

/// \ingroup Core
/// @{

/// \defgroup Events Events generated by Dasher modules.
/// @{

/// Edit event — fired when text is added, deleted, or converted.
/// Carries the edit type, the affected text, and the node that caused it.
class Dasher::CEditEvent {
  public:
    enum EditEventType { EDIT_OUTPUT = 1, EDIT_DELETE = 2, EDIT_CONVERT = 10, EDIT_PROTECT = 11 };

    CEditEvent(EditEventType iEditType, const std::string& sText, CDasherNode* pNode)
        : m_iEditType(iEditType), m_sText(sText), m_pNode(pNode) {}
    const EditEventType m_iEditType;
    const std::string m_sText;
    /// Node causing the event — allows calling GetSymbolProb, offset(), etc.
    /// if necessary.
    const CDasherNode* m_pNode;
};

/// @}

/// Signal/Slot event system — a typed publisher/subscriber mechanism.
///
/// Usage as a publisher (class that owns an Event):
/// \code
///   class CSettingsStore {
///   public:
///       Event<Parameter> OnParameterChanged;  // the signal
///   };
/// \endcode
///
/// Usage as a subscriber (RAII pattern — preferred for new code):
/// \code
///   class CMyModule {
///       Event<Parameter>::Subscription m_sub;  // member — auto-cleans
///   public:
///       CMyModule(CSettingsStore* s) {
///           m_sub = s->OnParameterChanged.Subscribe(
///               [this](Parameter p) { HandleChange(p); });
///       }
///       // No Unsubscribe needed in destructor — m_sub handles it.
///   };
/// \endcode
///
/// Legacy usage (void* key — still works, but requires manual cleanup):
/// \code
///   CMyModule(CSettingsStore* s) {
///       s->OnParameterChanged.Subscribe(this,
///           [this](Parameter p) { HandleChange(p); });
///   }
///   ~CMyModule() {
///       s->OnParameterChanged.Unsubscribe(this);
///   }
/// \endcode
template <typename... Args>
class Event {
  public:
    /// RAII subscription guard. Auto-unsubscribes when destroyed.
    ///
    /// Store as a member of the subscribing class. When the member goes
    /// out of scope (class destructor runs), the subscription is removed
    /// from the Event automatically — no manual Unsubscribe() needed.
    ///
    /// This eliminates the classic signal/slot lifetime hazard where a
    /// destroyed subscriber's callback remains in the Event's listener
    /// list, causing a use-after-free on the next Broadcast().
    class Subscription {
      public:
        Subscription() = default;
        ~Subscription() {
            if (m_event) m_event->unsubscribe(m_key);
        }

        // Movable (for assignment from Subscribe return value)
        Subscription(Subscription&& other) noexcept : m_event(other.m_event), m_key(other.m_key) {
            other.m_event = nullptr;
        }
        Subscription& operator=(Subscription&& other) noexcept {
            if (this != &other) {
                if (m_event) m_event->unsubscribe(m_key);
                m_event = other.m_event;
                m_key = other.m_key;
                other.m_event = nullptr;
            }
            return *this;
        }

        // Non-copyable (each subscription is a unique resource)
        Subscription(const Subscription&) = delete;
        Subscription& operator=(const Subscription&) = delete;

      private:
        friend class Event;
        Subscription(Event* event, void* key) : m_event(event), m_key(key) {}
        Event* m_event = nullptr;
        void* m_key = nullptr;
    };

    /// Subscribe with a void* key (legacy API — preserved for backward
    /// compatibility with existing callers).
    ///
    /// The key is typically `this` (the subscriber's pointer). It must
    /// be unique per subscriber per Event — subscribing with the same
    /// key twice replaces the previous callback.
    ///
    /// The caller MUST call Unsubscribe(this) before destruction to
    /// avoid dangling pointers in the Event's listener list.
    ///
    /// \param listener unique key for this subscriber (typically `this`)
    /// \param fn callback to invoke on Broadcast()
    void Subscribe(void* listener, const std::function<void(Args...)>& fn) {
        m_listeners[listener] = fn;
    }

    /// Subscribe without a key (RAII pattern — preferred for new code).
    ///
    /// Each call creates a unique internal key, so subscribers don't need
    /// to pass `this`. The returned Subscription must be stored (typically
    /// as a member) to keep the subscription alive.
    Subscription Subscribe(const std::function<void(Args...)>& fn) {
        // Use a synthetic unique key. Incrementing a counter avoids collisions
        // with real pointers (which are always even on most architectures).
        void* key = reinterpret_cast<void*>(m_nextSyntheticKey);
        m_nextSyntheticKey += 2; // skip even numbers (real pointers are even)
        m_listeners[key] = fn;
        return Subscription(this, key);
    }

    /// Remove a subscriber by its key (legacy API).
    /// Safe to call even if the key was never subscribed.
    void Unsubscribe(void* listener) { m_listeners.erase(listener); }

    /// Remove all subscribers.
    void Clear() { m_listeners.clear(); }

    /// Invoke all subscriber callbacks with the given arguments.
    ///
    /// Listeners are called in sorted key order (std::map guarantees
    /// deterministic iteration). This is important when subscribers have
    /// order-dependent side effects.
    void Broadcast(Args... args) {
        for (auto& [key, fn] : m_listeners) {
            if (fn) fn(args...);
        }
    }

  private:
    friend class Subscription;
    void unsubscribe(void* key) { m_listeners.erase(key); }

    // std::map (not unordered_map) for deterministic broadcast order.
    // The key is the subscriber's pointer (legacy) or a synthetic key (RAII).
    std::map<void*, std::function<void(Args...)>> m_listeners;

    // Counter for synthetic keys (used by the keyless Subscribe overload).
    // Starts at 1 (odd) to avoid colliding with real pointers (even).
    uintptr_t m_nextSyntheticKey = 1;
};
