// =============================================================================
// AUTOGENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by: python3 Scripts/generate_parameters.py
// Source:        settings_manifest.json
// =============================================================================

#include "Parameters.h"

#include "DasherTypes.h"

namespace Dasher{
  namespace Settings {

	const std::unordered_map<Parameter, const Parameter_Value> parameter_defaults = {
		{BP_DRAW_MOUSE_LINE          , Parameter_Value{"DrawMouseLine", PARAM_BOOL, Persistence::PERSISTENT, true, "When enabled, a line is drawn from the center of the screen to the current mouse position.", "Draw Mouse Line", Settings::UIControlType::Switch}},
		{BP_DRAW_MOUSE               , Parameter_Value{"DrawMouse", PARAM_BOOL, Persistence::PERSISTENT, true, "Displays a visual indicator at the current mouse position on the Dasher canvas.", "Show Mouse Position", Settings::UIControlType::Switch}},
		{BP_CURVE_MOUSE_LINE         , Parameter_Value{"CurveMouseLine", PARAM_BOOL, Persistence::PERSISTENT, false, "If 'Draw Mouse Line' is active, this makes the line follow a curved path that accounts for Dasher's non-linear coordinate space.", "Curve Mouse Line Path", Settings::UIControlType::Switch}},
		{BP_START_MOUSE              , Parameter_Value{"StartOnLeft", PARAM_BOOL, Persistence::PERSISTENT, true, "Enables starting and stopping the Dasher motion by moving the mouse.", "Start/Stop with Mouse", Settings::UIControlType::Switch}},
		{BP_START_SPACE              , Parameter_Value{"StartOnSpace", PARAM_BOOL, Persistence::PERSISTENT, false, "Enables using the spacebar to start and stop the Dasher motion.", "Start/Stop with Spacebar", Settings::UIControlType::Switch}},
		{BP_PALETTE_CHANGE           , Parameter_Value{"PaletteChange", PARAM_BOOL, Persistence::PERSISTENT, false, "Switch from color palette in setting automatically to the one provided in the alphabet.", "Auto Palette Switch"}},
		{BP_TURBO_MODE               , Parameter_Value{"TurboMode", PARAM_BOOL, Persistence::PERSISTENT, true, "Boost speed when holding key1 or right mouse button.", "Turbo Mode", Settings::UIControlType::Switch}},
		{BP_SMOOTH_PRESS_MODE        , Parameter_Value{"SmoothPressMode", PARAM_BOOL, Persistence::PERSISTENT, true, "Use Press-Input in the Smoothing-Input-Filter.", "Smoothing Pressure Mode", Settings::UIControlType::Switch}},
		{BP_SMOOTH_DRAW_MOUSE        , Parameter_Value{"SmoothDrawMouse", PARAM_BOOL, Persistence::PERSISTENT, false, "If enabled, the mouse indicator will show the smoothed position, not the raw input.", "Show Smoothed Mouse Pos", Settings::UIControlType::Switch}},
		{BP_SMOOTH_DRAW_MOUSE_LINE   , Parameter_Value{"SmoothDrawMouseLine", PARAM_BOOL, Persistence::PERSISTENT, false, "If enabled, the drawn mouse line will also be smoothed, showing the filtered input path.", "Draw Smoothed Mouse Line", Settings::UIControlType::Switch}},
		{BP_SMOOTH_ONLY_FORWARD      , Parameter_Value{"SmoothOnlyForward", PARAM_BOOL, Persistence::PERSISTENT, true, "If enabled, input smoothing is only applied when moving forward (zooming in), not when reversing.", "Smooth Forwards Only", Settings::UIControlType::Switch}},
		{BP_EXACT_DYNAMICS           , Parameter_Value{"ExactDynamics", PARAM_BOOL, Persistence::PERSISTENT, false, "Enables a more precise, but potentially less smooth, physics model for movement.", "Precise Dynamics", Settings::UIControlType::Switch}},
		{BP_AUTOCALIBRATE            , Parameter_Value{"Autocalibrate", PARAM_BOOL, Persistence::PERSISTENT, false, "Automatically adjusts the 'straight-ahead' point based on the user's average pointer position.", "Auto-Calibrate Target", Settings::UIControlType::Switch}},
		{BP_REMAP_XTREME             , Parameter_Value{"RemapXtreme", PARAM_BOOL, Persistence::PERSISTENT, false, "Distorts geometry to provide more space for navigating at extreme up/down angles.", "Remap Extreme Angles", Settings::UIControlType::Switch}},
		{BP_AUTO_SPEEDCONTROL        , Parameter_Value{"AutoSpeedControl", PARAM_BOOL, Persistence::PERSISTENT, true, "Automatically adjusts the maximum writing speed based on user performance.", "Automatic Speed Control", Settings::UIControlType::Switch}},
		{BP_LM_ADAPTIVE              , Parameter_Value{"LMAdaptive", PARAM_BOOL, Persistence::PERSISTENT, true, "Whether language model should learn as you enter text.", "Adaptive Language Model"}},
		{BP_NONLINEAR_Y              , Parameter_Value{"NonlinearY", PARAM_BOOL, Persistence::PERSISTENT, true, "Apply nonlinearities to Y axis (i.e. compress top & bottom).", "Nonlinear Y-Axis"}},
		{BP_STOP_OUTSIDE             , Parameter_Value{"PauseOutside", PARAM_BOOL, Persistence::PERSISTENT, false, "Automatically stops Dasher motion if the mouse cursor leaves the canvas area.", "Stop When Pointer Leaves", Settings::UIControlType::Switch}},
#ifdef TARGET_OS_IPHONE            	
		{BP_BACKOFF_BUTTON           , Parameter_Value{"BackoffButton", PARAM_BOOL, Persistence::PERSISTENT, false, "If enabled, releasing a button will cause Dasher to slightly zoom out, making it easier to correct mistakes.", "Back-off on Release", Settings::UIControlType::Switch}},
#else                              
		{BP_BACKOFF_BUTTON           , Parameter_Value{"BackoffButton", PARAM_BOOL, Persistence::PERSISTENT, true, "If enabled, releasing a button will cause Dasher to slightly zoom out, making it easier to correct mistakes.", "Back-off on Release", Settings::UIControlType::Switch}},
#endif                             
		{BP_TWOBUTTON_REVERSE        , Parameter_Value{"TwoButtonReverse", PARAM_BOOL, Persistence::PERSISTENT, false, "When enabled, the second button in a two-button setup will trigger a reverse/zoom-out action.", "Second Button Reverses", Settings::UIControlType::Switch}},
		{BP_2B_INVERT_DOUBLE         , Parameter_Value{"TwoButtonInvertDouble", PARAM_BOOL, Persistence::PERSISTENT, false, "Inverts the function of a double press on the second button.", "Invert Double Press Action", Settings::UIControlType::Switch}},
		{BP_SLOW_START               , Parameter_Value{"SlowStart", PARAM_BOOL, Persistence::PERSISTENT, false, "When enabled, Dasher will gradually accelerate to the desired speed from a standstill.", "Slow Start", Settings::UIControlType::Switch}},
		{BP_COPY_ALL_ON_STOP         , Parameter_Value{"CopyOnStop", PARAM_BOOL, Persistence::PERSISTENT, false, "Copy all text to clipboard whenever we stop.", "Copy on Stop"}},
		{BP_SPEAK_ALL_ON_STOP        , Parameter_Value{"SpeakOnStop", PARAM_BOOL, Persistence::PERSISTENT, false, "Speak all text whenever we stop.", "Speak on Stop"}},
		{BP_SPEAK_WORDS              , Parameter_Value{"SpeakWords", PARAM_BOOL, Persistence::PERSISTENT, false, "Speak words as they are written.", "Speak Words"}},
		{BP_GAME_HELP_DRAW_PATH      , Parameter_Value{"GameDrawPath", PARAM_BOOL, Persistence::PERSISTENT, true, "When we give help, show the shortest path to the target sentence.", "Draw Help Path"}},
		{BP_TWO_PUSH_RELEASE_TIME    , Parameter_Value{"TwoPushReleaseTime", PARAM_BOOL, Persistence::PERSISTENT, false, "Toggles timing behavior upon button release in two-push mode.", "Enable Release Time Logic", Settings::UIControlType::Switch}},
		{BP_SIMULATE_TRANSPARENCY    , Parameter_Value{"SimulateTransparency", PARAM_BOOL, Persistence::PERSISTENT, false, "Enable the internal color mixing and thus the need to support alpha blending in the renderer.", "Simulate Transparency"}},
		{LP_ORIENTATION              , Parameter_Value{"ScreenOrientation", PARAM_LONG, Persistence::PERSISTENT, -2l, "Screen Orientation.", "Screen Orientation"}},
		{LP_MAX_BITRATE              , Parameter_Value{"MaxBitRateTimes100", PARAM_LONG, Persistence::PERSISTENT, 80l, "The maximum writing speed. If 'Automatic Speed Control' is off, this is the fixed speed.", "Max Speed (bits/sec)", Settings::UIControlType::Step, 1, 1000, 1, 1}},
		{LP_FRAMERATE                , Parameter_Value{"FrameRate", PARAM_LONG, Persistence::EPHEMERAL, 3200l, "The target framerate for running automated demos.", "Demo Framerate"}},
		{LP_LANGUAGE_MODEL_ID        , Parameter_Value{"LanguageModelID", PARAM_LONG, Persistence::PERSISTENT, 0l, "LanguageModelID.", "Language Model"}},
		{LP_DASHER_FONTSIZE          , Parameter_Value{"DasherFontSize", PARAM_LONG, Persistence::PERSISTENT, 22l, "Font size reached at crosshair (in points).", "Dasher Font Size"}},
		{LP_MESSAGE_FONTSIZE         , Parameter_Value{"MessageFontSize", PARAM_LONG, Persistence::PERSISTENT, 14l, "Size of font for messages (in points).", "Message Font Size"}},
		{LP_SHAPE_TYPE               , Parameter_Value{"RenderStyle", PARAM_LONG, Persistence::PERSISTENT, static_cast<long>(Options::OVERLAPPING_RECTANGLE), "Shapes to render in (see Options::Rendering_Shape_Types).", "Node Shape"}},
		{LP_START_MODE               , Parameter_Value{"StartMode", PARAM_LONG, Persistence::PERSISTENT, static_cast<long>(Options::StartMode::none), "Movement Starting Mode.", "Start Mode", Settings::UIControlType::Enum, {{"None", Options::StartMode::none}, {"Circle Start", Options::StartMode::circle_start}, {"Mouse Position Start", Options::StartMode::mouse_pos_start}}}},
		{LP_UNIFORM                  , Parameter_Value{"UniformTimes1000", PARAM_LONG, Persistence::PERSISTENT, 50l, "Uniform probability weight (×1000). Higher values make less-probable symbols larger.", "Uniform Probability"}},
		{LP_MOUSEPOSDIST             , Parameter_Value{"MousePositionBoxDistance", PARAM_LONG, Persistence::PERSISTENT, 50l, "MousePositionBoxDistance.", "Mouse Position Distance"}},
		{LP_PY_PROB_SORT_THRES       , Parameter_Value{"PYProbabilitySortThreshold", PARAM_LONG, Persistence::PERSISTENT, 85l, "Sort converted syms in descending probability order up to this percentage.", "Pinyin Sort Threshold"}},
		{LP_MESSAGE_TIME             , Parameter_Value{"MessageTime", PARAM_LONG, Persistence::PERSISTENT, 2500l, "Time for which non-modal messages are displayed, in ms.", "Message Display Time"}},
		{LP_LM_MAX_ORDER             , Parameter_Value{"LMMaxOrder", PARAM_LONG, Persistence::PERSISTENT, 5l, "Maximum n-gram order for the language model.", "Max N-gram Order"}},
		{LP_LM_EXCLUSION             , Parameter_Value{"LMExclusion", PARAM_LONG, Persistence::PERSISTENT, 0l, "LMExclusion.", "Language Model Exclusion"}},
		{LP_LM_UPDATE_EXCLUSION      , Parameter_Value{"LMUpdateExclusion", PARAM_LONG, Persistence::PERSISTENT, 1l, "LMUpdateExclusion.", "LM Update Exclusion"}},
		{LP_LM_ALPHA                 , Parameter_Value{"LMAlpha", PARAM_LONG, Persistence::PERSISTENT, 49l, "Language model alpha blending parameter.", "LM Alpha"}},
		{LP_LM_BETA                  , Parameter_Value{"LMBeta", PARAM_LONG, Persistence::PERSISTENT, 77l, "Language model beta parameter.", "LM Beta"}},
		{LP_LM_MIXTURE               , Parameter_Value{"LMMixture", PARAM_LONG, Persistence::PERSISTENT, 50l, "Language model mixture parameter.", "LM Mixture"}},
		{LP_LINE_WIDTH               , Parameter_Value{"LineWidth", PARAM_LONG, Persistence::PERSISTENT, 1l, "Sets the thickness of the line drawn to the mouse cursor.", "Mouse Line Width", Settings::UIControlType::Step, 0, 1000, 1, 1}},
		{LP_GEOMETRY                 , Parameter_Value{"Geometry", PARAM_LONG, Persistence::PERSISTENT, static_cast<long>(Options::ScreenGeometry::old_style), "Changes the geometric projection used to display the Dasher world.", "Screen Geometry", Settings::UIControlType::Enum, {{"Old Style", Options::ScreenGeometry::old_style}, {"Square No Crosshair", Options::ScreenGeometry::square_no_xhair}, {"Squish", Options::ScreenGeometry::squish}, {"Squish and Log", Options::ScreenGeometry::squish_and_log}}}},
		{LP_LM_WORD_ALPHA            , Parameter_Value{"WordAlpha", PARAM_LONG, Persistence::PERSISTENT, 50l, "Alpha value for word-based model.", "Word Alpha"}},
		{LP_USER_LOG_LEVEL_MASK      , Parameter_Value{"UserLogLevelMask", PARAM_LONG, Persistence::PERSISTENT, 0l, "Controls level of user logging, 0 = none, 1 = short, 2 = detailed, 3 = both.", "User Log Level"}},
		{LP_ZOOMSTEPS                , Parameter_Value{"Zoomsteps", PARAM_LONG, Persistence::PERSISTENT, 32l, "Defines how many discrete steps are needed to zoom from the outer edge to the center.", "Zoom Steps", Settings::UIControlType::Step, 1, 63, 1, 1}},
		{LP_B                        , Parameter_Value{"ButtonMenuBoxes", PARAM_LONG, Persistence::PERSISTENT, 4l, "Number of boxes for button menu mode.", "B-Parameter", Settings::UIControlType::Step, 2, 10, 1, 1}},
		{LP_S                        , Parameter_Value{"ButtonMenuSafety", PARAM_LONG, Persistence::PERSISTENT, 25l, "Algorithmic constant related to speed or sensitivity in button mode.", "S-Parameter", Settings::UIControlType::Step, 0, 256, 1, 1}},
#ifdef TARGET_OS_IPHONE            	
		{LP_BUTTON_SCAN_TIME         , Parameter_Value{"ButtonMenuScanTime", PARAM_LONG, Persistence::PERSISTENT, 600l, "In modes that automatically scan options, this sets the time in milliseconds to wait at each step.", "Scan Time", Settings::UIControlType::Step, 0, 2000, 1, 100}},
#else                              
		{LP_BUTTON_SCAN_TIME         , Parameter_Value{"ButtonMenuScanTime", PARAM_LONG, Persistence::PERSISTENT, 0l, "In modes that automatically scan options, this sets the time in milliseconds to wait at each step.", "Scan Time", Settings::UIControlType::Step, 0, 2000, 1, 100}},
#endif                             
		{LP_R                        , Parameter_Value{"ButtonModeNonuniformity", PARAM_LONG, Persistence::PERSISTENT, 0l, "Button mode box non-uniformity.", "R-Parameter", Settings::UIControlType::Step, -89, 89, 1, 10}},
		{LP_RIGHTZOOM                , Parameter_Value{"ButtonCompassModeRightZoom", PARAM_LONG, Persistence::PERSISTENT, 5120l, "A multiplier affecting zoom speed when using compass mode.", "Right Zoom Multiplier", Settings::UIControlType::Step, 1024, 10240, 1024, 1024}},
#ifdef TARGET_OS_IPHONE            	
		{LP_NODE_BUDGET              , Parameter_Value{"NodeBudget", PARAM_LONG, Persistence::PERSISTENT, 1000l, "Target (min) number of node objects to maintain.", "Node Budget"}},
#else                              
		{LP_NODE_BUDGET              , Parameter_Value{"NodeBudget", PARAM_LONG, Persistence::PERSISTENT, 3000l, "Target (min) number of node objects to maintain.", "Node Budget"}},
#endif                             
		{LP_OUTLINE_WIDTH            , Parameter_Value{"OutlineWidth", PARAM_LONG, Persistence::PERSISTENT, 0l, "Absolute value is line width to draw boxes (fill iff >=0).", "Outline Width"}},
		{LP_TEXT_PADDING             , Parameter_Value{"TextPadding", PARAM_LONG, Persistence::PERSISTENT, 0l, "Pixel distance to inset the letters into the boxes.", "Text Padding"}},
		{LP_MIN_NODE_SIZE            , Parameter_Value{"MinNodeSize", PARAM_LONG, Persistence::PERSISTENT, 50l, "Minimum size of node (in dasher coords) to draw.", "Min Node Size"}},
		{LP_NONLINEAR_X              , Parameter_Value{"NonLinearX", PARAM_LONG, Persistence::PERSISTENT, 5l, "Nonlinear compression of X-axis (0 = none, higher = more extreme).", "Nonlinear X-Axis"}},
		{LP_AUTOSPEED_SENSITIVITY    , Parameter_Value{"AutospeedSensitivity", PARAM_LONG, Persistence::PERSISTENT, 100l, "Sensitivity of automatic speed control (percent).", "Auto-Speed Sensitivity"}},
		{LP_SOCKET_PORT              , Parameter_Value{"SocketPort", PARAM_LONG, Persistence::PERSISTENT, 20320l, "UDP/TCP socket to use for network socket input.", "Socket Port"}},
		{LP_SOCKET_INPUT_X_MIN       , Parameter_Value{"SocketInputXMinTimes1000", PARAM_LONG, Persistence::PERSISTENT, 0l, "Bottom of range of X values expected from network input.", "Socket X Min"}},
		{LP_SOCKET_INPUT_X_MAX       , Parameter_Value{"SocketInputXMaxTimes1000", PARAM_LONG, Persistence::PERSISTENT, 1000l, "Top of range of X values expected from network input.", "Socket X Max"}},
		{LP_SOCKET_INPUT_Y_MIN       , Parameter_Value{"SocketInputYMinTimes1000", PARAM_LONG, Persistence::PERSISTENT, 0l, "Bottom of range of Y values expected from network input.", "Socket Y Min"}},
		{LP_SOCKET_INPUT_Y_MAX       , Parameter_Value{"SocketInputYMaxTimes1000", PARAM_LONG, Persistence::PERSISTENT, 1000l, "Top of range of Y values expected from network input.", "Socket Y Max"}},
		{LP_CIRCLE_PERCENT           , Parameter_Value{"CirclePercent", PARAM_LONG, Persistence::PERSISTENT, 10l, "Percentage of nominal vertical range to use for radius of start circle.", "Circle Start Size"}},
		{LP_TWO_BUTTON_OFFSET        , Parameter_Value{"TwoButtonOffset", PARAM_LONG, Persistence::PERSISTENT, 1638l, "A positional or timing offset related to the second button's input.", "Two Button Offset", Settings::UIControlType::Step, 1024, 2048, 2048, 100}},
		{LP_HOLD_TIME                , Parameter_Value{"HoldTime", PARAM_LONG, Persistence::PERSISTENT, 1000l, "Minimum time (in ms) a button must be pressed to be considered a 'hold' instead of a 'tap'.", "Button Hold Time", Settings::UIControlType::Step, 10, 10000, 1000, 10}},
		{LP_MULTIPRESS_TIME          , Parameter_Value{"MultipressTime", PARAM_LONG, Persistence::PERSISTENT, 1000l, "The time window (in ms) within which multiple presses are counted as a single sequence.", "Multi-Press Window", Settings::UIControlType::Step, 100, 10000, 1000, 100}},
		{LP_SLOW_START_TIME          , Parameter_Value{"SlowStartTime", PARAM_LONG, Persistence::PERSISTENT, 1000l, "The time in milliseconds it takes to accelerate to full speed when 'Slow Start' is enabled.", "Slow Start Duration", Settings::UIControlType::Step, 0, 10000, 1000, 100}},
		{LP_SMOOTH_TAU               , Parameter_Value{"SmoothTau", PARAM_LONG, Persistence::PERSISTENT, 250l, "The time constant for input smoothing. Higher values result in smoother but less responsive input.", "Smoothing Amount", Settings::UIControlType::Step, 1, 1000, 1, 1}},
		{LP_TWO_PUSH_OUTER           , Parameter_Value{"TwoPushOuter", PARAM_LONG, Persistence::PERSISTENT, 1792l, "Defines the size of the outer zone for the 'two-push' control scheme.", "Two-Push Outer Zone", Settings::UIControlType::Step, 1024, 2048, 2048, 128}},
		{LP_TWO_PUSH_LONG            , Parameter_Value{"TwoPushLong", PARAM_LONG, Persistence::PERSISTENT, 512l, "Defines the minimum duration (in ms) of a 'long push'.", "Long Push Time", Settings::UIControlType::Step, 128, 1024, 2048, 128}},
		{LP_TWO_PUSH_SHORT           , Parameter_Value{"TwoPushShort", PARAM_LONG, Persistence::PERSISTENT, 80l, "Defines the maximum duration (in ms) of a 'short push'.", "Short Push Time", Settings::UIControlType::Step, 10, 90, 100, 1}},
		{LP_TWO_PUSH_TOLERANCE       , Parameter_Value{"TwoPushTolerance", PARAM_LONG, Persistence::PERSISTENT, 100l, "Positional tolerance for activating controls in the 'two-push' scheme.", "Two-Push Tolerance", Settings::UIControlType::Step, 50, 1000, 1, 10}},
		{LP_DYNAMIC_BUTTON_LAG       , Parameter_Value{"DynamicButtonLag", PARAM_LONG, Persistence::PERSISTENT, 50l, "Lag time specifically for the two-push dynamic mode.", "Dynamic Button Lag", Settings::UIControlType::Step, 0, 1000, 1, 25}},
		{LP_STATIC1B_TIME            , Parameter_Value{"Static1BTime", PARAM_LONG, Persistence::PERSISTENT, 2000l, "The time in milliseconds for static mode to scan from top to bottom.", "Static Zoom Time", Settings::UIControlType::Step, 100, 5000, 1, 100}},
		{LP_STATIC1B_ZOOM            , Parameter_Value{"Static1BZoom", PARAM_LONG, Persistence::PERSISTENT, 8l, "The amount of zoom applied per step in static mode.", "Static Zoom Step", Settings::UIControlType::Step, 1, 16, 1, 1}},
		{LP_DEMO_SPRING              , Parameter_Value{"DemoSpring", PARAM_LONG, Persistence::PERSISTENT, 100l, "A physics parameter for the automated cursor's 'springiness' in demo mode.", "Demo Springiness", Settings::UIControlType::Step, 0, 1000, 1, 1}},
		{LP_DEMO_NOISE_MEM           , Parameter_Value{"DemoNoiseMem", PARAM_LONG, Persistence::PERSISTENT, 100l, "A physics parameter controlling the 'memory' or consistency of random movements in demo mode.", "Demo Noise Memory", Settings::UIControlType::Step, 0, 1000, 1, 1}},
		{LP_DEMO_NOISE_MAG           , Parameter_Value{"DemoNoiseMag", PARAM_LONG, Persistence::PERSISTENT, 325l, "Controls the magnitude or intensity of random movements in demo mode.", "Demo Noise Magnitude", Settings::UIControlType::Step, 0, 1000, 1, 1}},
		{LP_MAXZOOM                  , Parameter_Value{"ClickMaxZoom", PARAM_LONG, Persistence::PERSISTENT, 200l, "Controls zoom mechanics in click mode.", "Zoom Sensitivity / Max Zoom", Settings::UIControlType::Step, 11, 400, 10, 1}},
		{LP_DYNAMIC_SPEED_INC        , Parameter_Value{"DynamicSpeedInc", PARAM_LONG, Persistence::PERSISTENT, 3l, "The amount the speed is increased by at each update interval if the user is navigating well.", "Auto-Speed Increment", Settings::UIControlType::Step, 1, 100, 1, 1}},
		{LP_DYNAMIC_SPEED_FREQ       , Parameter_Value{"DynamicSpeedFreq", PARAM_LONG, Persistence::PERSISTENT, 10l, "When 'Auto Speed Control' is on, this is how often the speed is re-evaluated.", "Auto-Speed Update Freq.", Settings::UIControlType::Step, 1, 1000, 1, 1}},
		{LP_DYNAMIC_SPEED_DEC        , Parameter_Value{"DynamicSpeedDec", PARAM_LONG, Persistence::PERSISTENT, 8l, "The amount the speed is decreased when the user reverses direction.", "Speed Reduction on Reverse", Settings::UIControlType::Step, 1, 99, 1, 1}},
		{LP_TAP_TIME                 , Parameter_Value{"TapTime", PARAM_LONG, Persistence::PERSISTENT, 200l, "The maximum time (in ms) for a stylus press to be considered a 'tap' for selecting items.", "Stylus Tap Time", Settings::UIControlType::Step, 1, 1000, 1, 25}},
#ifdef TARGET_OS_IPHONE            	
		{LP_MARGIN_WIDTH             , Parameter_Value{"MarginWidth", PARAM_LONG, Persistence::PERSISTENT, 500l, "Width of RHS margin (in Dasher co-ords).", "Margin Width"}},
#else                              
		{LP_MARGIN_WIDTH             , Parameter_Value{"MarginWidth", PARAM_LONG, Persistence::PERSISTENT, 300l, "Width of RHS margin (in Dasher co-ords).", "Margin Width"}},
#endif                             
		{LP_TARGET_OFFSET            , Parameter_Value{"TargetOffset", PARAM_LONG, Persistence::PERSISTENT, 0l, "A manual vertical offset to adjust the 'straight-ahead' point.", "Target Calibration Offset", Settings::UIControlType::Step, -100, 100, 400, 1}},
		{LP_X_LIMIT_SPEED            , Parameter_Value{"XLimitSpeed", PARAM_LONG, Persistence::PERSISTENT, 800l, "A multiplier that caps the maximum horizontal speed, making it easier to stay on target.", "Horizontal Speed Limit", Settings::UIControlType::Step, 1, 8000, 1536, 1}},
		{LP_GAME_HELP_DIST           , Parameter_Value{"GameHelpDistance", PARAM_LONG, Persistence::PERSISTENT, 1920l, "Distance of sentence from center to decide user needs help.", "Game Help Distance"}},
		{LP_GAME_HELP_TIME           , Parameter_Value{"GameHelpTime", PARAM_LONG, Persistence::PERSISTENT, 0l, "Time for which user must need help before help drawn.", "Game Help Time"}},
		{SP_ALPHABET_ID              , Parameter_Value{"AlphabetID", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "AlphabetID.", "Alphabet"}},
		{SP_ALPHABET_1               , Parameter_Value{"Alphabet1", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Alphabet History 1.", "Alphabet History 1"}},
		{SP_ALPHABET_2               , Parameter_Value{"Alphabet2", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Alphabet History 2.", "Alphabet History 2"}},
		{SP_ALPHABET_3               , Parameter_Value{"Alphabet3", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Alphabet History 3.", "Alphabet History 3"}},
		{SP_ALPHABET_4               , Parameter_Value{"Alphabet4", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Alphabet History 4.", "Alphabet History 4"}},
		{SP_COLOUR_ID                , Parameter_Value{"ColourID", PARAM_STRING, Persistence::PERSISTENT, std::string("Default"), "ColourID.", "Color Palette"}},
		{SP_DASHER_FONT              , Parameter_Value{"DasherFont", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "DasherFont.", "Dasher Font"}},
		{SP_GAME_TEXT_FILE           , Parameter_Value{"GameTextFile", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "User-specified file with strings to practice writing.", "Game Text File"}},
#ifdef TARGET_OS_IPHONE            	
		{SP_INPUT_FILTER             , Parameter_Value{"InputFilter", PARAM_STRING, Persistence::PERSISTENT, std::string("Stylus Control"), "Input filter used to provide the current control mode.", "Input Filter"}},
#else                              
		{SP_INPUT_FILTER             , Parameter_Value{"InputFilter", PARAM_STRING, Persistence::PERSISTENT, std::string("Normal Control"), "Input filter used to provide the current control mode.", "Input Filter"}},
#endif                             
		{SP_INPUT_DEVICE             , Parameter_Value{"InputDevice", PARAM_STRING, Persistence::PERSISTENT, std::string("Mouse Input"), "Driver for the input device.", "Input Device"}},
		{SP_BUTTON_MAPPINGS          , Parameter_Value{"ButtonMap", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Button assignments used in UI.", "Button Mappings"}},
		{SP_JOYSTICK_XAXIS           , Parameter_Value{"JoystickXAxis", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Joystick axis used for X-axis input.", "Joystick X Axis"}},
		{SP_JOYSTICK_YAXIS           , Parameter_Value{"JoystickYAxis", PARAM_STRING, Persistence::PERSISTENT, std::string(""), "Joystick axis used for Y-axis input.", "Joystick Y Axis"}},
	};

	ParameterType GetParameterType(Parameter parameter) {
		if (parameter_defaults.find(parameter) != parameter_defaults.end())
		{
			return parameter_defaults.at(parameter).type;
		}
		return PARAM_INVALID;
	}

	std::pair<Parameter, ParameterType> GetParameter(const std::string& parameterName) {

		for(auto& [key, value] : parameter_defaults)
		{
			if(value.storageName == parameterName) return {key, value.type};
		}
		return {PM_INVALID, PARAM_INVALID};
	}

	std::string GetParameterName(Parameter parameter) {
		if (parameter_defaults.find(parameter) != parameter_defaults.end())
		{
			return parameter_defaults.at(parameter).storageName;
		}
		return "";
	}

} //end namespace Settings
} //end namespace Dasher
