#!/usr/bin/env python3
"""Generate Parameters.cpp from settings_manifest.json.

Usage:
    python3 Scripts/generate_parameters.py [--manifest PATH] [--output PATH]

Defaults:
    --manifest  settings_manifest.json  (in repo root)
    --output    src/DasherCore/Parameters.cpp  (in repo root)
"""

import json
import os
import sys
import argparse

AUTOGEN_HEADER = """\
// =============================================================================
// AUTOGENERATED FILE — DO NOT EDIT DIRECTLY
// Generated by: python3 Scripts/generate_parameters.py
// Source:        settings_manifest.json
// =============================================================================
"""

TEMPLATE = """{header}
#include "Parameters.h"

#include "DasherTypes.h"

namespace Dasher{{
  namespace Settings {{

\tconst std::unordered_map<Parameter, const Parameter_Value> parameter_defaults = {{
{entries}\t}};

\tParameterType GetParameterType(Parameter parameter) {{
\t\tif (parameter_defaults.find(parameter) != parameter_defaults.end())
\t\t{{
\t\t\treturn parameter_defaults.at(parameter).type;
\t\t}}
\t\treturn PARAM_INVALID;
\t}}

\tstd::pair<Parameter, ParameterType> GetParameter(const std::string& parameterName) {{

\t\tfor(auto& [key, value] : parameter_defaults)
\t\t{{
\t\t\tif(value.storageName == parameterName) return {{key, value.type}};
\t\t}}
\t\treturn {{PM_INVALID, PARAM_INVALID}};
\t}}

\tstd::string GetParameterName(Parameter parameter) {{
\t\tif (parameter_defaults.find(parameter) != parameter_defaults.end())
\t\t{{
\t\t\treturn parameter_defaults.at(parameter).storageName;
\t\t}}
\t\treturn "";
\t}}

}} //end namespace Settings
}} //end namespace Dasher
"""


def escape_cpp_string(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def fmt_bool_default(val):
    return "true" if val else "false"


def fmt_long_default(param):
    if "enumDefault" in param:
        return param["enumDefault"]
    return f'{param["default"]}l'


def fmt_string_default(val):
    if val == "":
        return 'std::string("")'
    return f'std::string("{escape_cpp_string(val)}")'


def fmt_value(param):
    ptype = param["type"]
    if ptype == "bool":
        return fmt_bool_default(param["default"])
    elif ptype == "long":
        return fmt_long_default(param)
    elif ptype == "string":
        return fmt_string_default(param["default"])
    return ""


def fmt_platform_value(param, platform):
    ptype = param["type"]
    plat_val = param["platformDefaults"][platform]
    if ptype == "bool":
        return fmt_bool_default(plat_val)
    elif ptype == "long":
        return f'{plat_val}l'
    elif ptype == "string":
        return fmt_string_default(plat_val)
    return ""


def fmt_ui_type(ui_type):
    if ui_type and ui_type != "None":
        return f'Settings::UIControlType::{ui_type}'
    return None


def build_param_line(param, default_override=None):
    key = param["key"]
    storage = param["storageName"]
    ptype_map = {"bool": "PARAM_BOOL", "long": "PARAM_LONG", "string": "PARAM_STRING"}
    ptype_cpp = ptype_map[param["type"]]
    persistence = param.get("persistence", "PERSISTENT")
    default_val = default_override if default_override else fmt_value(param)
    desc = escape_cpp_string(param.get("description", ""))
    label = escape_cpp_string(param.get("label", ""))

    has_enum_values = "enumValues" in param
    has_range = all(k in param for k in ("min", "max"))

    if has_enum_values:
        enum_values = param["enumValues"]
        ui = fmt_ui_type(param.get("uiType"))
        ui_str = ui if ui else "Settings::UIControlType::None"
        pairs = ", ".join(
            f'{{"{ev["label"]}", {ev["cppExpr"]}}}' for ev in enum_values
        )
        return (
            f'\t\t{{{key:28s}, Parameter_Value{{"{storage}", {ptype_cpp}, '
            f'Persistence::{persistence}, {default_val}, "{desc}", "{label}", '
            f'{ui_str}, {{{pairs}}}, false, "{key}"}}}},'
        )

    if has_range:
        ui = fmt_ui_type(param.get("uiType"))
        ui_str = ui if ui else "Settings::UIControlType::None"
        return (
            f'\t\t{{{key:28s}, Parameter_Value{{"{storage}", {ptype_cpp}, '
            f'Persistence::{persistence}, {default_val}, "{desc}", "{label}", '
            f'{ui_str}, {param["min"]}, {param["max"]}, {param.get("divisor", 1)}, {param.get("step", 1)}, false, "{key}"}}}},'
        )

    ui = fmt_ui_type(param.get("uiType"))
    if ui:
        return (
            f'\t\t{{{key:28s}, Parameter_Value{{"{storage}", {ptype_cpp}, '
            f'Persistence::{persistence}, {default_val}, "{desc}", "{label}", '
            f'{ui}, false, "{key}"}}}},'
        )

    return (
        f'\t\t{{{key:28s}, Parameter_Value{{"{storage}", {ptype_cpp}, '
        f'Persistence::{persistence}, {default_val}, "{desc}", "{label}", '
        f'Settings::UIControlType::None, false, "{key}"}}}},'
    )


def generate_entry(param):
    has_platform = "platformDefaults" in param
    if not has_platform:
        return build_param_line(param) + "\n"

    lines = ""
    if "ios" in param["platformDefaults"]:
        ios_default = fmt_platform_value(param, "ios")
        lines += f'#ifdef TARGET_OS_IPHONE            \t\n'
        lines += build_param_line(param, default_override=ios_default) + "\n"
        lines += f'#else                              \n'
        lines += build_param_line(param) + "\n"
        lines += f'#endif                             \n'
    else:
        lines += build_param_line(param) + "\n"

    return lines


def generate(manifest_path, output_path):
    with open(manifest_path, 'r') as f:
        manifest = json.load(f)

    entries = ""
    for param in manifest["parameters"]:
        entries += generate_entry(param)

    content = TEMPLATE.format(header=AUTOGEN_HEADER, entries=entries)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Generated {output_path} from {manifest_path}")
    print(f"  {len(manifest['parameters'])} parameters")


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)

    parser = argparse.ArgumentParser(description="Generate Parameters.cpp from settings_manifest.json")
    parser.add_argument("--manifest", default=os.path.join(repo_root, "settings_manifest.json"),
                        help="Path to settings_manifest.json")
    parser.add_argument("--output", default=os.path.join(repo_root, "src", "DasherCore", "Parameters.cpp"),
                        help="Path to output Parameters.cpp")
    args = parser.parse_args()

    generate(args.manifest, args.output)


if __name__ == "__main__":
    main()
