#!/usr/bin/env python3
"""Tests for the settings_manifest code generation pipeline.

Verifies:
- extract_strings.py produces correct keys (enum-key format)
- extract_strings.py is idempotent
- apply_locale produces localized manifests
- generate_parameters.py produces valid Parameters.cpp
- All locale files have the same keys as English
- CMake can build with generated Parameters.cpp

Usage:
    python3 Scripts/test_pipeline.py
"""

import json
import os
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
MANIFEST_PATH = os.path.join(REPO_ROOT, "settings_manifest.json")
STRINGS_DIR = os.path.join(REPO_ROOT, "Strings")


def run(cmd, **kwargs):
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        print(f"  FAILED: {' '.join(cmd)}")
        print(f"  stderr: {result.stderr}")
        sys.exit(1)
    return result


def test_extract_keys_are_enum_format():
    with open(os.path.join(STRINGS_DIR, "strings_en.json")) as f:
        d = json.load(f)
    for key in d:
        assert key.startswith(("BP_", "LP_", "SP_")), f"Key not enum format: {key}"
    print(f"  ✓ All {len(d)} keys use enum format (BP_*/LP_*/SP_*)")


def test_extract_idempotent():
    result = run(
        [sys.executable, os.path.join(SCRIPT_DIR, "extract_strings.py"),
         "--output", "/dev/null"]
    )
    with open(os.path.join(STRINGS_DIR, "strings_en.json")) as f:
        existing = json.load(f)
    assert "219" in result.stdout, f"Expected 219 strings, got: {result.stdout}"
    print("  ✓ Extract is idempotent (219 strings)")


def test_locale_files_have_same_keys():
    with open(os.path.join(STRINGS_DIR, "strings_en.json")) as f:
        en = json.load(f)
    en_keys = set(en.keys())

    locale_files = [f for f in os.listdir(STRINGS_DIR)
                    if f.startswith("strings_") and f != "strings_en.json"]

    for lf in sorted(locale_files):
        with open(os.path.join(STRINGS_DIR, lf)) as f:
            loc = json.load(f)
        loc_keys = set(loc.keys())

        if en_keys != loc_keys:
            missing = en_keys - loc_keys
            extra = loc_keys - en_keys
            print(f"  ✗ {lf}: {len(missing)} missing, {len(extra)} extra keys")
            if missing:
                print(f"    Missing: {list(missing)[:3]}...")
            sys.exit(1)
        print(f"  ✓ {lf}: {len(loc_keys)} keys match strings_en.json")


def test_apply_locale():
    with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as tmp:
        tmp_path = tmp.name

    run([
        sys.executable, os.path.join(SCRIPT_DIR, "extract_strings.py"),
        "--apply", os.path.join(STRINGS_DIR, "strings_de.json"),
        "--locale", "de",
        "--output", tmp_path
    ])

    with open(tmp_path) as f:
        manifest = json.load(f)

    found_german = False
    for p in manifest["parameters"]:
        if p["key"] == "BP_DRAW_MOUSE_LINE":
            assert p["label"] != "Draw Mouse Line", "Label should be German"
            assert "Maus" in p["label"] or "maus" in p["label"].lower(), \
                f"Expected German label, got: {p['label']}"
            found_german = True
            break

    assert found_german, "BP_DRAW_MOUSE_LINE not found in manifest"
    os.unlink(tmp_path)
    print("  ✓ apply_locale produces localized manifest (German)")


def test_generate_parameters():
    with tempfile.NamedTemporaryFile(suffix=".cpp", delete=False) as tmp:
        tmp_path = tmp.name

    run([
        sys.executable, os.path.join(SCRIPT_DIR, "generate_parameters.py"),
        "--output", tmp_path
    ])

    with open(tmp_path) as f:
        content = f.read()

    assert "AUTOGENERATED" in content, "Missing autogen header"
    assert "BP_DRAW_MOUSE_LINE" in content, "Missing BP_DRAW_MOUSE_LINE enum key"
    assert 'enumKeyName' in content or '"BP_DRAW_MOUSE_LINE"' in content, \
        "Missing enum key name in generated code"

    # Count parameter entries by matching the {ENUM_KEY, Parameter_Value{ pattern
    import re
    entries = re.findall(r'\{(BP|LP|SP)_\w+', content)
    assert len(entries) >= 106, f"Expected >= 106 parameter entries, found {len(entries)}"

    os.unlink(tmp_path)
    print(f"  ✓ generate_parameters.py produces valid Parameters.cpp ({len(entries)} entries)")


def test_manifest_json_valid():
    with open(MANIFEST_PATH) as f:
        manifest = json.load(f)

    assert "parameters" in manifest
    params = manifest["parameters"]
    assert len(params) == 106

    required_fields = ["key", "storageName", "type", "label"]
    for p in params:
        for field in required_fields:
            assert field in p, f"Missing {field} in parameter {p.get('key', '???')}"
        assert "default" in p or "enumDefault" in p, \
            f"Missing default/enumDefault in parameter {p['key']}"

    print(f"  ✓ settings_manifest.json is valid ({len(params)} parameters)")


def test_enum_key_names_match():
    with open(os.path.join(STRINGS_DIR, "strings_en.json")) as f:
        strings = json.load(f)

    with open(MANIFEST_PATH) as f:
        manifest = json.load(f)

    manifest_keys = set()
    for p in manifest["parameters"]:
        k = p["key"]
        if p.get("label"):
            manifest_keys.add(f"{k}.label")
        if p.get("description"):
            manifest_keys.add(f"{k}.description")

    string_keys = set(strings.keys())

    missing_in_strings = manifest_keys - string_keys
    if missing_in_strings:
        print(f"  ✗ Keys in manifest but not in strings_en.json: {missing_in_strings}")
        sys.exit(1)

    print(f"  ✓ All manifest labels/descriptions have matching string keys")


def main():
    print("Testing DasherCore settings pipeline...\n")

    tests = [
        ("Manifest validity", test_manifest_json_valid),
        ("Extract: enum key format", test_extract_keys_are_enum_format),
        ("Extract: idempotent", test_extract_idempotent),
        ("Locale files: key parity", test_locale_files_have_same_keys),
        ("Locale files: match manifest", test_enum_key_names_match),
        ("Apply locale", test_apply_locale),
        ("Generate Parameters.cpp", test_generate_parameters),
    ]

    for name, fn in tests:
        print(f"Testing: {name}")
        fn()

    print(f"\n✓ All {len(tests)} pipeline tests passed!")


if __name__ == "__main__":
    main()
