// CAPI_locale.cpp — localization: locale loading, per-key overrides and
// lookup (todo.md Phase 2.5, moved verbatim from CAPI.cpp).
//
// Locale state is PROCESS-GLOBAL by design today: dasher_set_locale takes
// a ctx but the tables are shared across all contexts — pinned as a known
// wart by test_capi_contracts.cpp; todo.md 5.2 tracks making it
// per-context (a versioned, deliberate change).
//
// The tables are also read by parameter introspection (localized names /
// descriptions in dasher_get_parameter_info, CAPI_params.cpp), hence the
// capi:: accessors declared in CAPI_internal.h.

#include "CAPI_internal.h"

#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>

namespace {
// Process-global locale state (see file header).
std::string s_localeCode = "en";
std::unordered_map<std::string, std::string> s_localeStrings;
std::unordered_map<std::string, std::string> s_overrideStrings;
} // namespace

const std::unordered_map<std::string, std::string>& capi::localeStrings() {
    return s_localeStrings;
}
const std::unordered_map<std::string, std::string>& capi::overrideStrings() {
    return s_overrideStrings;
}

namespace {

// Append a Unicode codepoint to `out` as UTF-8 (1-3 bytes for the BMP;
// astral codepoints as a 4-byte sequence).
void appendUtf8(std::string& out, unsigned long cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

// Parse a flat { "key": "value", ... } strings file.
//
// Scope — read this before reusing: this is a flat string-map reader for
// BUNDLE-CONTROLLED files (Strings/strings_*.json, generated by
// Scripts/extract_strings.py and fed by translation tooling), NOT a
// general JSON parser. It is deliberately ~80 lines with no allocations
// beyond the result map and no external dependency — the strings format is
// exactly this shape, the files ship inside the app bundle, and the corpus
// is guarded by tests/test_locale_files.cpp so a malformed drop fails CI
// rather than users. If you need to parse arbitrary JSON, do NOT extend
// this: vendor a real parser at that boundary.
//
// Correctness within that scope (todo.md 5.1 — the original reader passed
// escapes through verbatim, so "\n" parsed as 'n' and a quoted-in-value \"
// broke the string structurally): the full JSON escape set is honoured,
// including \uXXXX with surrogate pairs.
std::unordered_map<std::string, std::string> parseStringsJson(const std::string& content) {
    std::unordered_map<std::string, std::string> result;
    std::string key, value;
    bool inString = false;
    bool escape = false;
    bool buildingKey = true;
    int depth = 0;

    // Append one decoded escape-sequence character (the char after the
    // backslash, or a decoded \uXXXX run) to the key or value being built.
    auto appendEscape = [&](const char* p, size_t& i, size_t end) -> void {
        char c = p[i];
        char out;
        switch (c) {
        case '"':
            out = '"';
            break;
        case '\\':
            out = '\\';
            break;
        case '/':
            out = '/';
            break;
        case 'b':
            out = '\b';
            break;
        case 'f':
            out = '\f';
            break;
        case 'n':
            out = '\n';
            break;
        case 'r':
            out = '\r';
            break;
        case 't':
            out = '\t';
            break;
        case 'u': {
            // \uXXXX (and a trailing surrogate pair forming an astral
            // codepoint). Hex digits are validated; malformed escapes
            // degrade to the literal text rather than corrupting framing.
            auto hex4 = [&](size_t from, unsigned long& cp) -> bool {
                cp = 0;
                for (int k = 0; k < 4; k++) {
                    char h = (from + k < end) ? p[from + k] : '\0';
                    cp <<= 4;
                    if (h >= '0' && h <= '9')
                        cp |= static_cast<unsigned long>(h - '0');
                    else if (h >= 'a' && h <= 'f')
                        cp |= static_cast<unsigned long>(h - 'a' + 10);
                    else if (h >= 'A' && h <= 'F')
                        cp |= static_cast<unsigned long>(h - 'A' + 10);
                    else
                        return false;
                }
                return true;
            };
            unsigned long cp = 0;
            if (!hex4(i + 1, cp)) {
                (buildingKey ? key : value) += 'u'; // literal 'u' — degrade
                return;
            }
            i += 4;
            if (cp >= 0xD800 && cp <= 0xDBFF && i + 7 < end && p[i + 1] == '\\' && p[i + 2] == 'u') {
                unsigned long lo = 0;
                if (hex4(i + 3, lo) && lo >= 0xDC00 && lo <= 0xDFFF) {
                    // Valid surrogate pair: combine and consume the low half.
                    cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
                    i += 6;
                }
            }
            std::string& target = buildingKey ? key : value;
            appendUtf8(target, cp);
            return;
        }
        default:
            // Unknown escape: keep the char as-is (lenient — the corpus is
            // controlled, and structural framing was already consumed).
            out = c;
            break;
        }
        (buildingKey ? key : value) += out;
    };

    for (size_t i = 0; i < content.size(); i++) {
        char c = content[i];

        if (escape) {
            size_t idx = i;
            appendEscape(content.c_str(), idx, content.size());
            i = idx;
            escape = false;
            continue;
        }

        if (c == '\\') {
            escape = true;
            continue;
        }

        if (c == '"') {
            if (inString) {
                inString = false;
                if (buildingKey && depth == 1) {
                    buildingKey = false;
                } else if (!buildingKey && depth == 1) {
                    result[key] = value;
                    key.clear();
                    value.clear();
                    buildingKey = true;
                }
            } else {
                inString = true;
            }
            continue;
        }

        if (inString) {
            if (buildingKey)
                key += c;
            else
                value += c;
            continue;
        }

        if (c == '{')
            depth++;
        else if (c == '}')
            depth--;
    }

    return result;
}
} // namespace

extern "C" {

// ── Localization ──────────────────────────────────────────────────────────

DASHER_API int dasher_set_locale(dasher_ctx* ctx, const char* locale) {
    if (!ctx) return -1;

    if (!locale || std::string(locale) == "en" || std::string(locale) == "") {
        s_localeCode = "en";
        s_localeStrings.clear();
        return 0;
    }

    std::string localeStr(locale);
    std::string path = ctx->dataDir;
#ifdef _WIN32
    path += "\\Strings\\strings_";
#else
    path += "/Strings/strings_";
#endif
    path += localeStr + ".json";

    std::ifstream file(path);
    if (!file.is_open()) return -1;

    std::stringstream ss;
    ss << file.rdbuf();
    s_localeStrings = parseStringsJson(ss.str());
    s_localeCode = localeStr;
    return 0;
}

DASHER_API const char* dasher_get_locale(dasher_ctx* ctx) {
    if (!ctx) return "en";
    ctx->scratch.stringBuf = s_localeCode;
    return ctx->scratch.stringBuf.c_str();
}

DASHER_API void dasher_set_string_override(dasher_ctx* ctx, const char* key, const char* value) {
    if (!ctx || !key) return;
    if (value) {
        s_overrideStrings[key] = value;
    } else {
        s_overrideStrings.erase(key);
    }
}

DASHER_API const char* dasher_get_localized_string(dasher_ctx* ctx, const char* key) {
    if (!ctx || !key) return nullptr;
    auto it = s_overrideStrings.find(key);
    if (it != s_overrideStrings.end()) {
        ctx->scratch.stringBuf = it->second;
        return ctx->scratch.stringBuf.c_str();
    }
    it = s_localeStrings.find(key);
    if (it != s_localeStrings.end()) {
        ctx->scratch.stringBuf = it->second;
        return ctx->scratch.stringBuf.c_str();
    }
    return nullptr;
}

} // extern "C"
