// CAPI_locale.cpp — localization: locale loading, per-key overrides and
// lookup (moved from CAPI.cpp in Phase 2.5; made per-context in 5.2).
//
// Since CAPI version 3, locale state is PER-CONTEXT: dasher_set_locale /
// dasher_get_locale / dasher_set_string_override / dasher_get_localized_
// string all operate on the calling ctx only. (Previously the tables were
// process-global — a wart pinned by the contracts tests, fixed
// deliberately with a version note.)
//
// One process-global remnant is ABI-forced: dasher_get_parameter_info
// (localized parameter names/descriptions) takes no ctx, so it reads the
// SNAPSHOT below. Semantics, pinned by the contracts tests:
// - strings: "last context wins" — the most recent successful
//   dasher_set_locale from any context replaces the snapshot wholesale
//   (set_locale("en") clears it);
// - overrides: a PER-KEY union across contexts (each key remembers its
//   most recent value from whichever context set it) that survives
//   dasher_destroy of the writing context, until a NULL set clears the
//   key or a fresh locale load replaces the strings it decorates.
// Multi-context frontends: set the locale on the context whose language
// the settings UI shows, and treat overrides as process-wide branding.
//
// The strings files are read with the flat-reader in this file — see its
// header comment for the deliberate scope decision (todo.md 5.1).

#include "CAPI_internal.h"

#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>

namespace {
// Process-global introspection snapshot (see file header): the strings and
// overrides seen by the ctx-less dasher_get_parameter_info.
std::unordered_map<std::string, std::string> s_introspectionStrings;
std::unordered_map<std::string, std::string> s_introspectionOverrides;
} // namespace

const std::unordered_map<std::string, std::string>& capi::localeStrings() {
    return s_introspectionStrings;
}
const std::unordered_map<std::string, std::string>& capi::overrideStrings() {
    return s_introspectionOverrides;
}

namespace {

// Append a Unicode codepoint to `out` as UTF-8 (1-3 bytes for the BMP;
// astral codepoints as a 4-byte sequence).
void appendUtf8(std::string& out, unsigned long cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

// Parse a flat { "key": "value", ... } strings file.
//
// Scope — read this before reusing: this is a flat string-map reader for
// BUNDLE-CONTROLLED files (Strings/strings_*.json, generated by
// Scripts/extract_strings.py and fed by translation tooling), NOT a
// general JSON parser. It is deliberately ~80 lines with no allocations
// beyond the result map and no external dependency — the strings format is
// exactly this shape, the files ship inside the app bundle, and the corpus
// is guarded by tests/test_locale_files.cpp so a malformed drop fails CI
// rather than users. If you need to parse arbitrary JSON, do NOT extend
// this: vendor a real parser at that boundary.
//
// Correctness within that scope (todo.md 5.1 — the original reader passed
// escapes through verbatim, so "\n" parsed as 'n' and a quoted-in-value \"
// broke the string structurally): the full JSON escape set is honoured,
// including \uXXXX with surrogate pairs. Known edge notes (inputs are
// controlled, so documented rather than defended against): \u0000 embeds
// a NUL (c_str() consumers see truncation); a lone surrogate emits CESU-8
// bytes rather than a replacement character.
// ok reports structural validity: a file is accepted only if it is ONE
// complete flat object — balanced braces, no unterminated string or escape,
// no key left without a value, no content (beyond whitespace) after the
// top-level close, no strings outside the object. A truncated or otherwise
// malformed file is rejected WHOLE (greptile, PR #92): installing the
// entries that happened to parse before the break would silently mix
// translated and English strings with no diagnostic.
std::unordered_map<std::string, std::string> parseStringsJson(const std::string& content, bool& ok) {
    std::unordered_map<std::string, std::string> result;
    std::string key, value;
    bool inString = false;
    bool escape = false;
    bool buildingKey = true;
    bool topClosed = false;
    bool sawEntry = false;
    // What token the grammar expects next between strings (see the token
    // switch below): a key after '{' or ',', ':' after a key, a string
    // value after ':', then ',' or the top-level '}'.
    enum class Tok { Key, Colon, Value, CommaOrClose };
    Tok expect = Tok::Key;
    int depth = 0;
    ok = true;

    // Append one decoded escape-sequence character (the char after the
    // backslash, or a decoded \uXXXX run) to the key or value being built.
    auto appendEscape = [&](const char* p, size_t& i, size_t end) -> void {
        char c = p[i];
        char out;
        switch (c) {
        case '"':
            out = '"';
            break;
        case '\\':
            out = '\\';
            break;
        case '/':
            out = '/';
            break;
        case 'b':
            out = '\b';
            break;
        case 'f':
            out = '\f';
            break;
        case 'n':
            out = '\n';
            break;
        case 'r':
            out = '\r';
            break;
        case 't':
            out = '\t';
            break;
        case 'u': {
            // \uXXXX (and a trailing surrogate pair forming an astral
            // codepoint). Hex digits are validated; malformed escapes
            // degrade to the literal text rather than corrupting framing.
            auto hex4 = [&](size_t from, unsigned long& cp) -> bool {
                cp = 0;
                for (int k = 0; k < 4; k++) {
                    char h = (from + k < end) ? p[from + k] : '\0';
                    cp <<= 4;
                    if (h >= '0' && h <= '9')
                        cp |= static_cast<unsigned long>(h - '0');
                    else if (h >= 'a' && h <= 'f')
                        cp |= static_cast<unsigned long>(h - 'a' + 10);
                    else if (h >= 'A' && h <= 'F')
                        cp |= static_cast<unsigned long>(h - 'A' + 10);
                    else
                        return false;
                }
                return true;
            };
            unsigned long cp = 0;
            if (!hex4(i + 1, cp)) {
                (buildingKey ? key : value) += 'u'; // literal 'u' — degrade
                return;
            }
            i += 4;
            if (cp >= 0xD800 && cp <= 0xDBFF && i + 6 < end && p[i + 1] == '\\' && p[i + 2] == 'u') {
                unsigned long lo = 0;
                if (hex4(i + 3, lo) && lo >= 0xDC00 && lo <= 0xDFFF) {
                    // Valid surrogate pair: combine and consume the low half.
                    cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
                    i += 6;
                }
            }
            std::string& target = buildingKey ? key : value;
            appendUtf8(target, cp);
            return;
        }
        default:
            // Unknown escape: keep the char as-is (lenient — the corpus is
            // controlled, and structural framing was already consumed).
            out = c;
            break;
        }
        (buildingKey ? key : value) += out;
    };

    for (size_t i = 0; i < content.size(); i++) {
        char c = content[i];

        if (escape) {
            size_t idx = i;
            appendEscape(content.c_str(), idx, content.size());
            i = idx;
            escape = false;
            continue;
        }

        if (c == '\\') {
            escape = true;
            continue;
        }

        if (c == '"') {
            if (inString) {
                inString = false;
                if (buildingKey && depth == 1) {
                    buildingKey = false;
                    expect = Tok::Colon; // key finished: a ':' must follow
                } else if (!buildingKey && depth == 1) {
                    result[key] = value;
                    key.clear();
                    value.clear();
                    buildingKey = true;
                    sawEntry = true;
                    expect = Tok::CommaOrClose; // pair finished
                }
            } else if (depth >= 1) {
                // A string may only open where the grammar expects one:
                // a key after '{' or ',', a value after ':'.
                if (expect == Tok::Key) {
                    buildingKey = true;
                    inString = true;
                } else if (expect == Tok::Value) {
                    buildingKey = false;
                    inString = true;
                } else {
                    ok = false; // string where ':'/','/'}' was expected
                }
            } else {
                ok = false; // string outside the top-level object
            }
            continue;
        }

        if (topClosed) {
            if (c != ' ' && c != '\t' && c != '\r' && c != '\n') ok = false; // trailing content
            continue;
        }

        if (inString) {
            if (buildingKey)
                key += c;
            else
                value += c;
            continue;
        }

        // Token grammar between strings — flat {"k":"v", ...} files only
        // (greptile follow-up, PR #92: end-state checks alone accepted
        // numbers-as-values, missing ':'/',' separators and arbitrary junk
        // — worse, {"a":1,"b":"2"} mis-paired b's value under key "a").
        // Outside a string the ONLY legal tokens are braces, one ':' after
        // each key, one ',' between pairs, and whitespace.
        switch (c) {
        case '{':
            if (++depth > 1) ok = false; // flat format: no nested objects
            break;
        case '}':
            if (--depth == 0) {
                // Close is legal after a pair, or for the empty object —
                // never mid-pair and never trailing a comma.
                if (expect == Tok::CommaOrClose || (expect == Tok::Key && !sawEntry)) {
                    topClosed = true;
                } else {
                    ok = false;
                }
            } else {
                ok = false;
            }
            break;
        case ':':
            if (depth == 1 && expect == Tok::Colon)
                expect = Tok::Value;
            else
                ok = false;
            break;
        case ',':
            if (depth == 1 && expect == Tok::CommaOrClose)
                expect = Tok::Key;
            else
                ok = false;
            break;
        default:
            if (c != ' ' && c != '\t' && c != '\r' && c != '\n') ok = false; // junk token (numbers, words, ...)
            break;
        }
    }

    // Whole-file validity: exactly one complete object, nowhere mid-token.
    if (depth != 0 || !topClosed || inString || escape || !buildingKey) ok = false;
    return result;
}
} // namespace

extern "C" {

// ── Localization ──────────────────────────────────────────────────────────

DASHER_API int dasher_set_locale(dasher_ctx* ctx, const char* locale) {
    if (!ctx) return -1;

    if (!locale || std::string(locale) == "en" || std::string(locale) == "") {
        ctx->locale.code = "en";
        ctx->locale.strings.clear();
        s_introspectionStrings.clear();
        return 0;
    }

    std::string localeStr(locale);
    std::string path = ctx->dataDir;
#ifdef _WIN32
    path += "\\Strings\\strings_";
#else
    path += "/Strings/strings_";
#endif
    path += localeStr + ".json";

    std::ifstream file(path);
    if (!file.is_open()) return -1;

    std::stringstream ss;
    ss << file.rdbuf();
    bool ok = true;
    auto parsed = parseStringsJson(ss.str(), ok);
    if (!ok) return -1; // malformed: rejected whole, ctx locale untouched
    ctx->locale.strings = std::move(parsed);
    ctx->locale.code = localeStr;
    // The ctx-less parameter introspection follows the most recent locale
    // (see the file header — ABI: dasher_get_parameter_info takes no ctx).
    s_introspectionStrings = ctx->locale.strings;
    return 0;
}

DASHER_API const char* dasher_get_locale(dasher_ctx* ctx) {
    if (!ctx) return "en";
    ctx->scratch.stringBuf = ctx->locale.code;
    return ctx->scratch.stringBuf.c_str();
}

DASHER_API void dasher_set_string_override(dasher_ctx* ctx, const char* key, const char* value) {
    if (!ctx || !key) return;
    if (value) {
        ctx->locale.overrides[key] = value;
        s_introspectionOverrides[key] = value;
    } else {
        ctx->locale.overrides.erase(key);
        s_introspectionOverrides.erase(key);
    }
}

DASHER_API const char* dasher_get_localized_string(dasher_ctx* ctx, const char* key) {
    if (!ctx || !key) return nullptr;
    auto it = ctx->locale.overrides.find(key);
    if (it != ctx->locale.overrides.end()) {
        ctx->scratch.stringBuf = it->second;
        return ctx->scratch.stringBuf.c_str();
    }
    it = ctx->locale.strings.find(key);
    if (it != ctx->locale.strings.end()) {
        ctx->scratch.stringBuf = it->second;
        return ctx->scratch.stringBuf.c_str();
    }
    return nullptr;
}

} // extern "C"
